# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class HelloStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greeter = channel.unary_unary(
        '/grpcresolver.hello.Hello/Greeter',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloResponse.FromString,
        )
    self.GreeterResponseStream = channel.unary_stream(
        '/grpcresolver.hello.Hello/GreeterResponseStream',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloResponse.FromString,
        )
    self.StreamGreeter = channel.stream_unary(
        '/grpcresolver.hello.Hello/StreamGreeter',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloResponse.FromString,
        )
    self.StreamGreeterResponseStream = channel.stream_stream(
        '/grpcresolver.hello.Hello/StreamGreeterResponseStream',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloResponse.FromString,
        )


class HelloServicer(object):

  def Greeter(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GreeterResponseStream(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamGreeter(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamGreeterResponseStream(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greeter': grpc.unary_unary_rpc_method_handler(
          servicer.Greeter,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloResponse.SerializeToString,
      ),
      'GreeterResponseStream': grpc.unary_stream_rpc_method_handler(
          servicer.GreeterResponseStream,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloResponse.SerializeToString,
      ),
      'StreamGreeter': grpc.stream_unary_rpc_method_handler(
          servicer.StreamGreeter,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloResponse.SerializeToString,
      ),
      'StreamGreeterResponseStream': grpc.stream_stream_rpc_method_handler(
          servicer.StreamGreeterResponseStream,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcresolver.hello.Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
