# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='grpcresolver.hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhello.proto\x12\x12grpcresolver.hello\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x02\n\x05Hello\x12P\n\x07Greeter\x12 .grpcresolver.hello.HelloRequest\x1a!.grpcresolver.hello.HelloResponse\"\x00\x12`\n\x15GreeterResponseStream\x12 .grpcresolver.hello.HelloRequest\x1a!.grpcresolver.hello.HelloResponse\"\x00\x30\x01\x12X\n\rStreamGreeter\x12 .grpcresolver.hello.HelloRequest\x1a!.grpcresolver.hello.HelloResponse\"\x00(\x01\x12h\n\x1bStreamGreeterResponseStream\x12 .grpcresolver.hello.HelloRequest\x1a!.grpcresolver.hello.HelloResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='grpcresolver.hello.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpcresolver.hello.HelloRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=66,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='grpcresolver.hello.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpcresolver.hello.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:grpcresolver.hello.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:grpcresolver.hello.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class HelloStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Greeter = channel.unary_unary(
          '/grpcresolver.hello.Hello/Greeter',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloResponse.FromString,
          )
      self.GreeterResponseStream = channel.unary_stream(
          '/grpcresolver.hello.Hello/GreeterResponseStream',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloResponse.FromString,
          )
      self.StreamGreeter = channel.stream_unary(
          '/grpcresolver.hello.Hello/StreamGreeter',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloResponse.FromString,
          )
      self.StreamGreeterResponseStream = channel.stream_stream(
          '/grpcresolver.hello.Hello/StreamGreeterResponseStream',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloResponse.FromString,
          )


  class HelloServicer(object):

    def Greeter(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GreeterResponseStream(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StreamGreeter(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StreamGreeterResponseStream(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Greeter': grpc.unary_unary_rpc_method_handler(
            servicer.Greeter,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloResponse.SerializeToString,
        ),
        'GreeterResponseStream': grpc.unary_stream_rpc_method_handler(
            servicer.GreeterResponseStream,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloResponse.SerializeToString,
        ),
        'StreamGreeter': grpc.stream_unary_rpc_method_handler(
            servicer.StreamGreeter,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloResponse.SerializeToString,
        ),
        'StreamGreeterResponseStream': grpc.stream_stream_rpc_method_handler(
            servicer.StreamGreeterResponseStream,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'grpcresolver.hello.Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHelloServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Greeter(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GreeterResponseStream(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StreamGreeter(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StreamGreeterResponseStream(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHelloStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Greeter(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Greeter.future = None
    def GreeterResponseStream(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    def StreamGreeter(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    StreamGreeter.future = None
    def StreamGreeterResponseStream(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_Hello_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('grpcresolver.hello.Hello', 'Greeter'): HelloRequest.FromString,
      ('grpcresolver.hello.Hello', 'GreeterResponseStream'): HelloRequest.FromString,
      ('grpcresolver.hello.Hello', 'StreamGreeter'): HelloRequest.FromString,
      ('grpcresolver.hello.Hello', 'StreamGreeterResponseStream'): HelloRequest.FromString,
    }
    response_serializers = {
      ('grpcresolver.hello.Hello', 'Greeter'): HelloResponse.SerializeToString,
      ('grpcresolver.hello.Hello', 'GreeterResponseStream'): HelloResponse.SerializeToString,
      ('grpcresolver.hello.Hello', 'StreamGreeter'): HelloResponse.SerializeToString,
      ('grpcresolver.hello.Hello', 'StreamGreeterResponseStream'): HelloResponse.SerializeToString,
    }
    method_implementations = {
      ('grpcresolver.hello.Hello', 'Greeter'): face_utilities.unary_unary_inline(servicer.Greeter),
      ('grpcresolver.hello.Hello', 'GreeterResponseStream'): face_utilities.unary_stream_inline(servicer.GreeterResponseStream),
      ('grpcresolver.hello.Hello', 'StreamGreeter'): face_utilities.stream_unary_inline(servicer.StreamGreeter),
      ('grpcresolver.hello.Hello', 'StreamGreeterResponseStream'): face_utilities.stream_stream_inline(servicer.StreamGreeterResponseStream),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Hello_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('grpcresolver.hello.Hello', 'Greeter'): HelloRequest.SerializeToString,
      ('grpcresolver.hello.Hello', 'GreeterResponseStream'): HelloRequest.SerializeToString,
      ('grpcresolver.hello.Hello', 'StreamGreeter'): HelloRequest.SerializeToString,
      ('grpcresolver.hello.Hello', 'StreamGreeterResponseStream'): HelloRequest.SerializeToString,
    }
    response_deserializers = {
      ('grpcresolver.hello.Hello', 'Greeter'): HelloResponse.FromString,
      ('grpcresolver.hello.Hello', 'GreeterResponseStream'): HelloResponse.FromString,
      ('grpcresolver.hello.Hello', 'StreamGreeter'): HelloResponse.FromString,
      ('grpcresolver.hello.Hello', 'StreamGreeterResponseStream'): HelloResponse.FromString,
    }
    cardinalities = {
      'Greeter': cardinality.Cardinality.UNARY_UNARY,
      'GreeterResponseStream': cardinality.Cardinality.UNARY_STREAM,
      'StreamGreeter': cardinality.Cardinality.STREAM_UNARY,
      'StreamGreeterResponseStream': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'grpcresolver.hello.Hello', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
